##############################
### HCF+ by Adbi and kbalu ###
##############################

Debug: 'true'

# Database
DATABASE_HOST: 'localhost'
DATABASE_PORT: 3306
DATABASE_DATABSE: hcf+
DATABASE_USER: root
DATABASE_PASSWORD: ''

# Main scoreboard
Scoreboard_title: '&6HCF+ &7- &eMap &6#1'
Scoreboard:
  - "&7\u250c\u2500"
  - "&7\u2502 &eFaction: &6%faction%"
  - "&7\u2502 &eLocation: &6%location%"
  - "&7\u2502 &eMoney: &6$%money%"
  - "&7\u2502 &eClass: &6%class%"
  - "&7\u2514\u2500"
  - "empty"
  - "&7\u258d &e%customtimers%"
  - "&7\u258d &eEOTW: &6%eotw%"
  - "&7\u258d &eSOTW: &6%sotw%"
  - "&7\u258d &eGapple: &6%gapple_cd%"
  - "&7\u258d &eOP: &6%opgapple_cd%"
  - "&7\u258d &eStuck: &6%stuck_timer%"
  - "&7\u258d &eSpawn Tag: &6%spawntag%"
  - "&7\u258d &ePVP Tag:: &6%pvp_timer%"
  - "&7\u258d &ePearl: &6%ep_cd%"
  - "&7\u258d &eBard energy: &6%bard_energy%"

Admin_Scoreboard_Title: '&6HCF+ &7- &eAdmin Duty'
Admin_Scoreboard:
  - "&7&m----------------------"
  - "&4* &cStaff Panel"
  - "&f* &7Visible: &f%invisible%"
  - "&f* &7Chatmode: &f%chat_mode%"
  - "&f* &7Players: &f%online_players%"
  - "&f* &7TPS: &a%tps%"
  - "&7&m----------------------&r"
  - "&7\u258d &e%customtimers%"
  - "&7\u258d &eEOTW: &6%eotw%"
  - "&7\u258d &eSOTW: &6%sotw%"
  - "&7\u258d &eGapple: &6%gapple_cd%"
  - "&7\u258d &eOP: &6%opgapple_cd%"
  - "&7\u258d &eStuck: &6%stuck_timer%"
  - "&7\u258d &eSpawn Tag: &6%spawntag%"
  - "&7\u258d &ePearl: &6%ep_cd%"
  - "&7\u258d &eBard energy: &6%bard_energy%"

# Freeze (/freeze <player>)
Freeze:
  Ban: true
  Reason: 'You leaved when you are froze!'
  BanTimeSeconds: 300

# HCF world name
World_name: 'world'

# World width in blocks
World_width: '10000'

# If true, then ban player when are died
Deathban: 'false'
Death_time_seconds: '30'

Claim_price_multiplier: '1.5'

# Faction home teleport
teleport_delay_in_seconds: '10'

# Combat time in seconds
Combat_time: '30'

# When archer shoot a player
# Tag timer in seconds
Archer_tag: 30

# Starting balance for new factions
Faction_default_balance: '1000'

# Bard energy cost
strength: 20
speed: 40
jump_boost: 30
resistance: 40
fire_resistance: 20
regeneration: 20
absorption: 20
haste: 30

# EOTW time in minutes
EOTW_time: 60

# Blacklisted Rank Names
Blacklisted-rankNames:
  - "Dick"
  - "You"
  - "Adbi"

enderpearl_delay: '30'
Golden_Apple_Cooldown: '10'
OP_Golden_Apple_Cooldown: '3600'
Spawn_location: 0 64 0 0 0
Enchant_xp_cost: '20'
WORLD_BORDER_DISTANCE: '1000'
STUCK_TIMER_DURATION: '30'
KOTH_TIME: '15'
MAX_FACTION_MEMBERS: '7'
WARZONE_SIZE: '500'
MAX_DTR: '5.5'
DEATH_DTR: '1.0'
DTR_REGEN_TIME_SECONDS: '60'

